Repository JinOptimist/NET14, pull requests merged in 2022-02, with the labels that each got.

#150 Team social/task149 add social menu
  Net14/Net14/Menu.cs
  Net14/TeamSocial/Social.cs
  Net14/TeamSocial/SocialMenu.cs
Labels: SocialWeb

#154 TeamSocial/Task151 add post class
  Net14/TeamSocial/Post.cs
Labels: SocialWeb

#157 Wall class was added
  Net14/TeamSocial/Post.cs
  Net14/TeamSocial/Social.cs
  Net14/TeamSocial/User.cs
  Net14/TeamSocial/Wall.cs
Labels: SocialWeb

#158 Task156_Add SocialDrawerClass
  Net14/TeamSocial/Social.cs
  Net14/TeamSocial/SocialDrawer.cs
  Net14/TeamSocial/SocialMenu.cs
  Net14/TeamSocial/User.cs
Labels: SocialWeb

#163 Team social/task159 add friend property to user class
  Net14/TeamSocial/Post.cs
  Net14/TeamSocial/User.cs
Labels: SocialWeb

#176 TeamSocial/Task172 Add _currentUser field
  Net14/TeamSocial/Social.cs
Labels: SocialWeb

#179 TeamSocial/Task178_AddPostMethod add some comments and fix some bags
  Net14/TeamSocial/Post.cs
  Net14/TeamSocial/Social.cs
  Net14/TeamSocial/SocialDrawer.cs
  Net14/TeamSocial/SocialMenu.cs
  Net14/TeamSocial/User.cs
  Net14/TeamSocial/Wall.cs
Labels: SocialWeb

#187 Task182_CreateFriendWall
  Net14/TeamSocial/FriendsWall.cs
  Net14/TeamSocial/Models/User.cs
  Net14/TeamSocial/Social.cs
  Net14/TeamSocial/SocialBuilder.cs
  Net14/TeamSocial/SocialMenu.cs
Labels: SocialWeb

#186 Task129_Basket
  Net14/Team_Store/Basket.cs
  Net14/Team_Store/Goods.cs
  Net14/Team_Store/Program.cs
Labels: TeamStore

#194 Team social/task191 add recomendation of friends
  Net14/TeamSocial/FriendsWall.cs
  Net14/TeamSocial/Models/User.cs
  Net14/TeamSocial/Social.cs
  Net14/TeamSocial/SocialMenu.cs
Labels: SocialWeb

#190 TeamSocial/Task189_AddCountryAndCityProperties
  Net14/TeamSocial/Models/User.cs
Labels: SocialWeb

#197 TeamSocial/Task196_AddPasswordHashing
  Net14/TeamSocial/Models/User.cs
  Net14/TeamSocial/Social.cs
Labels: SocialWeb

#167 TeamCalendar/Task153 create calendar
  Net14/Calendar/CalendarDrawer.cs
  Net14/Calendar/Class1.cs
  Net14/Calendar/CreateCalendar.cs
  Net14/Calendar/Days/BaseDays.cs
  Net14/Calendar/Days/Day.cs
  Net14/Calendar/Days/EmptyDay.cs
  Net14/Calendar/DirectionForMonth.cs
  Net14/Calendar/IMonthLevel.cs
  Net14/Calendar/MonthLevel.cs
  Net14/HTML/index.html
  Net14/HTML/style.css
  Net14/Net14/Menu.cs
  Net14/Net14/Net14.csproj
Labels: Calendar

#212 Team social/task 183 create post wall 1
  Net14/TeamSocial/Models/Post.cs
  Net14/TeamSocial/Models/User.cs
  Net14/TeamSocial/PostWall.cs
  Net14/TeamSocial/SocialBuilder.cs
  Net14/TeamSocial/SocialDrawer.cs
  Net14/TeamSocial/SocialMenu.cs
Labels: SocialWeb
